// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"encoding/json"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	recover2 "github.com/gofiber/fiber/v2/middleware/recover"
	"productservice/config"
	"productservice/internal/cache"
	"productservice/internal/database"
	"productservice/internal/grpc/client"
	"productservice/internal/grpc/provider"
	"productservice/internal/handler"
	"productservice/internal/middleware"
	"productservice/internal/repository"
	"productservice/internal/router"
	"productservice/internal/service"
	"time"
)

// Injectors from server.go:

func New() (*fiber.App, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	db, err := database.NewPostgresDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	redisClient, err := cache.NewRedisClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	productRepository := repository.NewProductRepository(db, redisClient)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	clientConn, cleanup, err := provider.ProvideGRPCConnection(configConfig)
	if err != nil {
		return nil, nil, err
	}
	authClient := client.NewAuthClient(clientConn)
	rateRepository := repository.NewRateRepository(db, redisClient, authClient)
	rateService := service.NewRateService(rateRepository)
	rateHandler := handler.NewRateHandler(rateService)
	routerHandler := router.NewRouterHandler(productHandler, rateHandler)
	authMiddleware := middleware.NewAuthMiddleware(authClient)
	middlewareMiddleware := middleware.NewMiddleware(authMiddleware)
	app := NewServer(routerHandler, middlewareMiddleware)
	return app, func() {
		cleanup()
	}, nil
}

// server.go:

func NewServer(router2 *router.RouterHandler, md *middleware.Middleware) *fiber.App {
	app := fiber.New(fiber.Config{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 5 * time.Second,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	app.Use(logger.New())
	app.Use(cors.New())
	recoverConfig := recover2.ConfigDefault
	app.Use(recover2.New(recoverConfig))
	router2.
		InitRouter(app, md)

	return app
}
