// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"encoding/json"
	"github.com/agris/user-service/internal/cache"
	"github.com/agris/user-service/internal/config"
	"github.com/agris/user-service/internal/database"
	"github.com/agris/user-service/internal/handler"
	"github.com/agris/user-service/internal/middleware"
	"github.com/agris/user-service/internal/repository"
	"github.com/agris/user-service/internal/router"
	"github.com/agris/user-service/internal/service"
	"github.com/agris/user-service/pkg/jwtMg"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	recover2 "github.com/gofiber/fiber/v2/middleware/recover"
	"time"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgresDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := cache.NewRedisClient(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db, client)
	jwtManager := jwtMg.NewJWTManager(configConfig)
	redisRepository := cache.NewRedisRepository(client)
	authService := service.NewAuthService(userRepository, jwtManager, configConfig, redisRepository)
	authHandler := handler.NewAuthHandler(authService)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	middlewareMiddleware := middleware.NewMiddleware(jwtManager)
	routerHandler := router.NewRouterHandler(authHandler, userHandler, middlewareMiddleware)
	app := NewServer(routerHandler)
	return app, nil
}

// server.go:

func NewServer(router2 *router.RouterHandler) *fiber.App {
	app := fiber.New(fiber.Config{
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 5 * time.Second,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
	})

	app.Use(logger.New())
	app.Use(cors.New())
	recoverConfig := recover2.ConfigDefault
	app.Use(recover2.New(recoverConfig))
	router2.
		InitRouter(app)

	return app
}
