// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/agris/user-service/internal/cache"
	"github.com/agris/user-service/internal/config"
	"github.com/agris/user-service/internal/database"
	"github.com/agris/user-service/internal/grpc/interceptor"
	"github.com/agris/user-service/internal/grpc/service_grpc"
	"github.com/agris/user-service/internal/repository"
	"github.com/agris/user-service/internal/service"
	"github.com/agris/user-service/pkg/jwtMg"
	"google.golang.org/grpc"
)

// Injectors from wire_grpc.go:

// InitGRPCServer khởi tạo TẤT CẢ dependencies và tạo gRPC server
func InitGRPCServer() (*grpc.Server, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	db, err := database.NewPostgresDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	client, err := cache.NewRedisClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(db, client)
	jwtManager := jwtMg.NewJWTManager(configConfig)
	redisRepository := cache.NewRedisRepository(client)
	authService := service.NewAuthService(userRepository, jwtManager, configConfig, redisRepository)
	userService := service.NewUserService(userRepository)
	authGRPCService := service_grpc.NewAuthGRPCService(authService, jwtManager, userService)
	authInterceptor := interceptor.NewAuthInterceptor(jwtManager)
	server, cleanup, err := NewGRPCServer(configConfig, authGRPCService, authInterceptor)
	if err != nil {
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}
