// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/agris/user-service/internal/cache"
	"github.com/agris/user-service/internal/config"
	"github.com/agris/user-service/internal/database"
	"github.com/agris/user-service/internal/grpc/service_grpc"
	"github.com/agris/user-service/internal/repository"
	"github.com/agris/user-service/internal/service"
	"github.com/agris/user-service/pkg/jwtMg"
)

// Injectors from wire_grpc.go:

func InitGRPCServer() (*service_grpc.AuthGRPCService, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewPostgresDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := cache.NewRedisClient(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db, client)
	jwtManager := jwtMg.NewJWTManager(configConfig)
	redisRepository := cache.NewRedisRepository(client)
	authService := service.NewAuthService(userRepository, jwtManager, configConfig, redisRepository)
	userService := service.NewUserService(userRepository)
	authGRPCService := service_grpc.NewAuthGRPCService(authService, jwtManager, userService)
	return authGRPCService, nil
}
